spring:
  cloud:
    consul:
      discovery:
        hostname: host.docker.internal
        health-check-path: /actuator/health
        health-check-interval: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
