spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/${DB_MYSQL_NAME}
    username: ${DB_MYSQL_USER}
    password: ${DB_MYSQL_PASSWORD}
  cloud:
    consul:
      discovery:
        port: 8085
jwt:
  expiration: 86400000
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}
  
server:
  port: 8085
