spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: ${DB_MONGO_NAME}
      username: ${DB_MONGO_USER}
      password: ${DB_MONGO_PASSWORD}
      authentication-database: admin
  cloud:
    consul:
      discovery:
        port: 8083

server:
  port: 8083
